Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.Bootstrap: true
    nodeTypes:
      groups:
        neosrulezBootstrap:
          position: 'end'
          label: NeosRulez.Bootstrap:Main:neosrulezBootstrap
        neosrulezBootstrapMultimedia:
          position: 'after neosrulezBootstrap'
          label: NeosRulez.Bootstrap:Main:neosrulezBootstrapMultimedia
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Bootstrap:
            - Main
            - 'NodeTypes/*'
            - 'NodeTypes/Content/*'
            - 'NodeTypes/Component/*'
            - 'NodeTypes/Mixin/*'
      inspector:
        dataTypes:
          'Neos\Media\Domain\Model\ImageInterface':
            editorOptions:
              accept: 'image/png,image/jpeg,image/gif,image/svg+xml'
              features:
                resize: false
NeosRulez:
  Bootstrap:
    headerLogoPath: 'Images/Logo.svg'
    headerLogoPackage: 'NeosRulez.Bootstrap'
    headerLogoAltText: 'NeosRulez.Bootstrap'
    navbarAlignment: 'right'
    navbarFluid: false
    navbarSticky: true
    navbarBackground: 'bg-white'
    navbarBreakpoint: 'lg'
    navbarHover: false
    clickableParent: false
    useYouTubeNoCookie: true
    navbarIdentifier: true
#    googleMapsApiKey: 'XyzaazaSyAEpcE4tniLTPaCDTm9e9-7h9dPBgHjfs'
    fontawesome:
      publicResourcePath: 'resource://NeosRulez.Bootstrap/Public/Assets'
      version: '5.15.2'
#      version: '6.2.0'
#      licence: 'pro'
