NeosRulez:
  Bootstrap:
    headerLogoPath: 'Images/Logo.png'
    headerLogoPackage: 'Default.Site'
    headerLogoAltText: 'Default'
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Bootstrap:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
      inspector:
        dataTypes:
          'Neos\Media\Domain\Model\ImageInterface':
            editorOptions:
              features:
                resize: TRUE
      navigateComponent:
        nodeTree:
          loadingDepth: 999
        structureTree:
          loadingDepth: 999
    nodeTypes:
      groups:
        bootstrapnodetypes:
          position: 'end'
          label: NeosRulez.Bootstrap:Main:nodetypes
        extended:
          position: 'end'
          label: NeosRulez.Bootstrap:Main:extended
    fusion:
      autoInclude:
        NeosRulez.Bootstrap: true
  ContentRepository:
    contentDimensions:
      'language':
        label: NeosRulez.Bootstrap:Main:language
        icon: 'icon-language'
        default: 'de'
        defaultPreset: 'de'
        presets:
          'de':
            label: 'Deutsch'
            values: ['de']
            uriSegment: 'de'
  Form:
    presets:
      default:
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://NeosRulez.Bootstrap/Private/Form/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              containerClassAttribute: input
              elementClassAttribute: 'form-control'
              elementErrorClassAttribute: error
            renderingOptions:
              renderableNameInTemplate: element
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:MultipleSelectDropdown':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:Checkbox':
            properties:
              elementClassAttribute: form-check-input